### ISSUE TITLE
usage with Express 4 router

### ISSUE THREAD

**Issue by kokujin** [cermati/route-label#5]
I am trying to use this with Express 4 routes

in "routes/posts.js"

```

module.exports = function(app){
  var router = require('route-label')(app);

  router.get('all.posts', '/posts/:id', function(req, res, next) {
    res.send('Test route ');
  });

  return router;
};
```

And then in "app.js", I do this

```
app.use('/posts', require('./routes/posts')(app));
```

This, unfortunately, does not work, I get this traceback:

```
/Users/kokujin/Development/Research/namedroutes_test/node_modules/express/lib/application.js:97
    this.request.__proto__ = parent.request;
                           ^

TypeError: Cyclic __proto__ value
    at IncomingMessage.set __proto__ (native)
    at EventEmitter.onmount (/Users/kokujin/Development/Research/namedroutes_test/node_modules/express/lib/application.js:97:28)
    at emitOne (events.js:90:13)
    at EventEmitter.emit (events.js:182:7)
    at EventEmitter.<anonymous> (/Users/kokujin/Development/Research/namedroutes_test/node_modules/express/lib/application.js:237:8)
    at Array.forEach (native)
    at EventEmitter.use (/Users/kokujin/Development/Research/namedroutes_test/node_modules/express/lib/application.js:216:7)
    at Object.<anonymous> (/Users/kokujin/Development/Research/namedroutes_test/app.js:25:5)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
```

Any idea about what I'm doing wrong? Thanks

**Comment by gyosh** [comment]
Hi @kokujin ,

You will need to create new express instance inside the posts submodule. Try this.

In app.js:

``` js
var router = require('route-label')(app);
router.use('posts', '/posts', require('./routes/posts'));
```

In routes/posts.js:

``` js
var app = require('express')();
var router = require('route-label')(app);
router.get('all', '/:id', function(req, res, next) {
  res.send('Test route ');
});
```

You should get route called `posts.all` which refer to `/posts/:id`

**Comment by kokujin** [comment]
For every route submodule, create a new Express instance? I think thats a deal-breaker for me. Thanks anyways.

**Comment by gyosh** [comment]
@kokujin got it, I made follow up issue https://github.com/cermati/route-label/issues/7 which we will be working on it

Thank you for pointing it out

**Comment by gyosh** [comment]
@kokujin anyway, it turns out the current version can support using `express.Routing()` instance instead of `express()` instance for each sub module. You may want to check this sample project: https://github.com/cermati/route-label-sample
